version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "05:11"
    open-pull-requests-limit: 10
    reviewers:
      - sukhmancs
    assignees:
      - sukhmancs
