name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 16 * * *"}]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
    
      - name: 🦑 General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          config_timezone: America/Toronto
          base_indepth: yes
          config_order: base.header, isocalendar, languages, topics, repositories, habits, wakatime
          plugin_repositories: yes
          plugin_repositories_featured: nixos-config-main, react-native-instagram-clone, amber-train
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_ignored: html, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot, scala, c, c++, python, ejs, css, shell
          plugin_languages_limit: 4
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_topics_sort: stars 
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%   
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}

      # - name: 🦑 Medias
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: medias.svg
      #     # Current configuration doesn't require a GitHub token
      #     token: NOT_NEEDED

      #     # Options
      #     base: ""
      #     base_hireable: yes
      #     config_timezone: America/Toronto
      #     plugin_anilist: yes
      #     plugin_anilist_limit: 2
      #     plugin_anilist_limit_characters: 22
      #     plugin_anilist_medias: anime
      #     plugin_anilist_sections: favorites, characters
      #     plugin_anilist_shuffle: yes
      #     plugin_anilist_user: Ermoth
      #     plugin_music: yes
      #     plugin_music_limit: 6
      #     plugin_music_mode: recent
      #     plugin_music_played_at: yes
      #     plugin_music_playlist: https://open.spotify.com/embed/playlist/6qQwnl5AuJfdMY4RG769he
      #     plugin_music_provider: spotify
      #     plugin_music_token: "${{ secrets.CLIENT_ID }}, ${{ secrets.CLIENT_SECRET }}, ${{ secrets.REFRESH_TOKEN }}"
      #     plugin_music_time_range: short
      #     plugin_music_top_type: tracks
      #     plugin_music_user: Toohen
      #     plugin_pagespeed: yes
      #     plugin_pagespeed_screenshot: yes
      #     plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
      #     plugin_pagespeed_url: https://sukhmansingh.netlify.app/about
